// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5o6TAjZXirg7CEJWJdgT_AFboUQGu9Rg',
    appId: '1:359583839238:web:936f22f03c1f8d74e3ff87',
    messagingSenderId: '359583839238',
    projectId: 'nailexam-b26d8',
    authDomain: 'nailexam-b26d8.firebaseapp.com',
    storageBucket: 'nailexam-b26d8.firebasestorage.app',
    measurementId: 'G-2GMNX0XW6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOzc1Nnrug8mLLoD_IAzV3tXFHaW7KOiw',
    appId: '1:359583839238:android:5707412f430be289e3ff87',
    messagingSenderId: '359583839238',
    projectId: 'nailexam-b26d8',
    storageBucket: 'nailexam-b26d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4hli74uz-Zsr24HE73vPHLNmDCIICWfM',
    appId: '1:359583839238:ios:09fe14d6495e39f2e3ff87',
    messagingSenderId: '359583839238',
    projectId: 'nailexam-b26d8',
    storageBucket: 'nailexam-b26d8.firebasestorage.app',
    iosBundleId: 'com.example.nailexam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4hli74uz-Zsr24HE73vPHLNmDCIICWfM',
    appId: '1:359583839238:ios:09fe14d6495e39f2e3ff87',
    messagingSenderId: '359583839238',
    projectId: 'nailexam-b26d8',
    storageBucket: 'nailexam-b26d8.firebasestorage.app',
    iosBundleId: 'com.example.nailexam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5o6TAjZXirg7CEJWJdgT_AFboUQGu9Rg',
    appId: '1:359583839238:web:f789f221b4d927c7e3ff87',
    messagingSenderId: '359583839238',
    projectId: 'nailexam-b26d8',
    authDomain: 'nailexam-b26d8.firebaseapp.com',
    storageBucket: 'nailexam-b26d8.firebasestorage.app',
    measurementId: 'G-XQSJ17HXD6',
  );
}
